import Navbar from "./Navigation/page";
import Footer from "./Footer/page";

export const metadata = {
  title: "KyleCodes",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
